# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `rails
# db:schema:load`. When creating a new database, `rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 2019_06_14_035818) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "clients", force: :cascade do |t|
    t.bigint "company_id"
    t.string "client_code"
    t.string "charge_code"
    t.string "coy_debtor"
    t.string "credit_terms"
    t.string "client_type"
    t.string "contract_no"
    t.string "reference_no"
    t.string "contract_date"
    t.string "contract_completion"
    t.string "contract_value"
    t.string "billing_cycle"
    t.string "contract_narration"
    t.string "client_activated"
    t.string "client_inactive"
    t.string "cas_bill_cycle"
    t.boolean "cas_consolidate"
    t.string "cas_narration"
    t.string "cas_fee_schedule"
    t.string "std_start_time"
    t.string "std_finish_time"
    t.string "last_cycle"
    t.boolean "cont_contract"
    t.string "cont_repet_amt"
    t.string "publichol"
    t.string "cascode_rate1"
    t.string "account_contact"
    t.string "cascode_rate3"
    t.string "cascode_rate4"
    t.string "casrate1_oride"
    t.string "casrate2_oride"
    t.string "casrate3_oride"
    t.string "casrate4_oride"
    t.string "category"
    t.string "cas_cat"
    t.string "mon_svce_code"
    t.string "mon_svce_rate"
    t.boolean "monitoring"
    t.string "generic_name"
    t.string "last_gendate"
    t.string "client_class"
    t.string "normal_day"
    t.string "hours_pperiod"
    t.string "repet_charge_ac"
    t.string "repet_service_desc"
    t.string "cas1_charge_to"
    t.string "case2_charge_to"
    t.string "cas3_charge_to"
    t.string "cas4_charge_to"
    t.string "monitoring_charge_to"
    t.string "monitor_service_desc"
    t.string "cas_category_description"
    t.string "cost_method"
    t.string "cost_rate"
    t.string "std_hours_schedule"
    t.string "client_category"
    t.string "inv_jnl"
    t.string "division"
    t.string "department"
    t.string "institution"
    t.string "speciality"
    t.string "beds"
    t.string "occupancy"
    t.string "contract_ref"
    t.string "lab_attch_flag"
    t.string "clab_attch_flag"
    t.string "discount_code"
    t.string "monitoring_class"
    t.string "monitoring_company"
    t.string "perm_payclass"
    t.string "cas_payclass"
    t.boolean "whcchge"
    t.string "salesman"
    t.string "debtor_clerk"
    t.string "std_phol_schedule"
    t.boolean "apply_stdhours"
    t.string "rebate_ctrl"
    t.string "rebate_cat"
    t.string "rebate_code"
    t.string "dflt_car"
    t.string "charge_type"
    t.string "minimum_hours"
    t.boolean "fix_rate"
    t.string "fixed_rate_period"
    t.boolean "suppress_messages"
    t.boolean "debtors_ledger"
    t.string "cost_centre"
    t.string "perm_grade"
    t.string "cas_grade"
    t.boolean "oncharge_ot"
    t.boolean "time_scheduling"
    t.string "review_date"
    t.string "shift_names"
    t.boolean "inactive"
    t.string "area_bldg"
    t.string "service_levels"
    t.string "casual_service_desc"
    t.string "region"
    t.string "cas_cost_rate"
    t.string "casinv_detail_lvl"
    t.string "scheduling_seq"
    t.string "response_inv_flag"
    t.string "invoice_statement_flag"
    t.boolean "invoice_ordno_split"
    t.boolean "print_cust_bill_instructions"
    t.boolean "print_response_on_invoice"
    t.boolean "show_rate_type"
    t.string "default_cost_centre"
    t.string "response_time"
    t.string "dflt_bud_emptype"
    t.string "send_invoice_by"
    t.string "email_address"
    t.boolean "brief_required"
    t.string "invoice_format"
    t.string "addendum_format"
    t.boolean "summ_rpt_option"
    t.string "summ_rpt_narrative"
    t.string "attach_files"
    t.string "attach_comments"
    t.string "seasonality_group"
    t.boolean "role_rate_mapping"
    t.string "vendor_cost_code"
    t.boolean "apply_award_schedule"
    t.boolean "roletype_split"
    t.boolean "do_not_invoice"
    t.string "store_no"
    t.boolean "include_acn_invoice"
    t.string "care_plans"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["client_code"], name: "index_clients_on_client_code"
    t.index ["company_id"], name: "index_clients_on_company_id"
  end

  create_table "cnas", force: :cascade do |t|
    t.bigint "company_id"
    t.string "code"
    t.string "account"
    t.string "name"
    t.string "inits"
    t.string "given_names"
    t.string "contact"
    t.string "phone_h"
    t.string "phone_b"
    t.string "phone_o"
    t.string "facsimile"
    t.string "address"
    t.string "suburb"
    t.string "state"
    t.string "pcode"
    t.string "post_address"
    t.string "post_suburb"
    t.string "post_state"
    t.string "post_pcode"
    t.string "create_date"
    t.string "shortcode"
    t.string "acn"
    t.string "bsbcode"
    t.string "paymethod"
    t.string "bank_account"
    t.string "bank_drawer"
    t.string "phone_name"
    t.string "phone_address"
    t.string "phone_number"
    t.string "phone_ext"
    t.string "contact_name"
    t.string "contact_address"
    t.string "contact_number"
    t.string "contact_ext"
    t.string "photo_id"
    t.string "video_id"
    t.string "map_ref"
    t.string "abn"
    t.string "phone_type"
    t.boolean "adobe_sent"
    t.string "gl_sw_ft"
    t.string "gl_sw_ca"
    t.string "gl_sickleave"
    t.string "gl_wcomp"
    t.string "gl_super"
    t.string "gl_al_taken"
    t.string "gl_ptax"
    t.string "gl_al_accrued"
    t.string "gl_dept"
    t.string "gl_wages"
    t.string "gl_lve_loading"
    t.string "gl_lsl"
    t.string "gl_clearing"
    t.string "web_user_id"
    t.string "client_code"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["code"], name: "index_cnas_on_code"
    t.index ["company_id"], name: "index_cnas_on_company_id"
  end

  create_table "companies", force: :cascade do |t|
    t.string "title"
    t.boolean "is_admin", default: false
    t.integer "users_count"
  end

  create_table "employees", force: :cascade do |t|
    t.bigint "company_id"
    t.string "employee_code"
    t.string "employee_a_street"
    t.string "employee_a_suburb"
    t.string "employee_a_post_code"
    t.string "employee_a_city"
    t.string "employee_a_state"
    t.string "a_phone"
    t.string "a_second_phone"
    t.string "marital_status"
    t.string "sex"
    t.date "birth_date"
    t.date "employment_date"
    t.date "termination_date"
    t.string "security_license_number"
    t.date "security_license_expiry_date"
    t.string "first_name"
    t.string "middle_name"
    t.string "surname"
    t.string "employ_company"
    t.string "pay_advice"
    t.string "super_fund_no"
    t.string "employment_type"
    t.string "pay_class"
    t.string "tax_file_number"
    t.string "tax_schedule"
    t.string "tax_rebates"
    t.string "group_catagory"
    t.string "bank_acc_name"
    t.string "bank_bsb"
    t.string "bank_acc_no"
    t.string "payment_method"
    t.string "allowance"
    t.string "allow_amt"
    t.string "sick_leave"
    t.string "leave"
    t.string "lsl"
    t.string "super_fund"
    t.string "bank_amount"
    t.string "pay_cycle"
    t.string "default_cost_ctr"
    t.string "accrued_sick_leave"
    t.string "accrued_annual_leave"
    t.string "accrued_lsl"
    t.string "accrued_rdo"
    t.string "relatives_name"
    t.string "relative_contact"
    t.string "license_type"
    t.string "emp_pay_ref"
    t.boolean "hecs"
    t.string "alias"
    t.string "deduct_payee"
    t.string "eft_lodgement_no"
    t.string "coy_sgl"
    t.string "vol_sgl"
    t.string "vol_sgl_amt"
    t.string "vol_policy"
    t.string "rel_relation"
    t.string "vested_coy_sgl"
    t.string "vested_emp_sgl"
    t.string "term_reas_code"
    t.string "override_income"
    t.string "override_base_hours"
    t.boolean "apply_override_base_hours"
    t.string "emp_class_oride"
    t.string "alldedn_start"
    t.string "alldedn_end"
    t.string "alldedn_mthd"
    t.string "alldedn_bal"
    t.string "bcn"
    t.string "leave_code_oride"
    t.string "mobile_phone"
    t.boolean "term_flag"
    t.string "leave_base"
    t.date "tax_waiver_date"
    t.string "country"
    t.string "photo_path"
    t.string "preffered_name"
    t.date "review_date"
    t.string "personal_details"
    t.string "weight"
    t.string "height"
    t.string "dependants"
    t.string "other_notes"
    t.string "ban_location"
    t.date "ban_location_date"
    t.string "ban_location_reason"
    t.date "ban_location_end_date"
    t.string "title"
    t.string "former_name"
    t.string "prev_name"
    t.string "citizenship"
    t.boolean "resident"
    t.boolean "work_permit"
    t.string "contact_types"
    t.string "contact_numbers"
    t.string "contact_notes"
    t.string "pay_advice_delivery"
    t.string "depend_surname"
    t.string "depend_fname"
    t.string "depend_relationship"
    t.date "depend_birthdate"
    t.boolean "rehire"
    t.string "skill_code"
    t.date "attain_date"
    t.string "skill_comment"
    t.boolean "oncall"
    t.boolean "close_shifts"
    t.boolean "long_week"
    t.boolean "long_day"
    t.string "role_types"
    t.string "work_regions"
    t.string "nationality"
    t.boolean "sfss"
    t.date "last_accrue_date"
    t.boolean "print_bank_details"
    t.string "cost_centre"
    t.string "cost_centre_split"
    t.string "class_change_date"
    t.string "class_change_type"
    t.string "class_change_class"
    t.string "class_change_reason"
    t.string "transfered_employeeid"
    t.string "mail_address"
    t.string "mail_suburb"
    t.string "mail_state"
    t.string "mail_postcode"
    t.string "mail_country"
    t.string "licence_image"
    t.string "skills_image"
    t.string "notes"
    t.string "eff_entitle_date"
    t.string "eff_aleave_code"
    t.string "eff_sickleave_code"
    t.string "eff_rdo_code"
    t.string "eff_lsl_code"
    t.string "position_group_code"
    t.date "position_date"
    t.date "system_start_date"
    t.string "change_status"
    t.string "super_change_date"
    t.string "super_change_fund"
    t.string "super_change_policy"
    t.string "super_change_note"
    t.boolean "pay_skill"
    t.string "pay_location"
    t.boolean "excess_hours_pref"
    t.boolean "traineeship_flag"
    t.date "training_review_date"
    t.string "emp_email_address"
    t.string "web_user_id"
    t.string "latitude"
    t.string "longitude"
    t.string "status_date"
    t.string "status_code"
    t.string "inactive_date"
    t.string "inactive_reason"
    t.string "rehire_reason"
    t.string "employee_logs"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["company_id"], name: "index_employees_on_company_id"
    t.index ["employ_company"], name: "index_employees_on_employ_company"
    t.index ["employee_code"], name: "index_employees_on_employee_code"
  end

  create_table "rosters", force: :cascade do |t|
    t.bigint "company_id"
    t.string "employee_code"
    t.string "long_id"
    t.string "customer"
    t.boolean "penalty"
    t.string "fee_sched"
    t.string "fee_code"
    t.string "payclass"
    t.string "btime"
    t.string "paid_hours"
    t.string "tsht_type"
    t.string "tsht_code"
    t.string "tsht_rate"
    t.string "tsht_qty"
    t.string "nml_code"
    t.string "nml_hours"
    t.string "nml_rate"
    t.string "t12_code"
    t.string "t12_hours"
    t.string "t12_rate"
    t.string "dbl_code"
    t.string "dbl_hours"
    t.string "dbl_rate"
    t.string "oth_code"
    t.string "oth_hours"
    t.string "oth_rate"
    t.string "abft_code"
    t.string "abft_rate"
    t.string "abft_qty"
    t.string "dbft_code"
    t.string "dbft_rate"
    t.string "dbft_qty"
    t.string "aaft_code"
    t.string "aaft_rate"
    t.string "aaft_qty"
    t.string "daft_code"
    t.string "daft_rate"
    t.string "daft_qty"
    t.string "shift_day"
    t.string "shift_hours"
    t.string "pay_details"
    t.string "invoice_ref"
    t.string "meal_brk_start"
    t.string "meal_brk_end"
    t.string "wrk_hrs_paid"
    t.string "chg_shift_day"
    t.string "chg_shift_hours"
    t.boolean "unpaid_status"
    t.boolean "casual"
    t.string "activity_stime"
    t.string "activity_etime"
    t.string "activity_proj"
    t.string "activity_task"
    t.string "activity_details"
    t.string "hour_type"
    t.string "modified_by"
    t.string "modified_date"
    t.string "shift_zone"
    t.string "time_code"
    t.string "gl_codes"
    t.string "cust_orderno"
    t.string "fax_lodgement"
    t.string "response_event"
    t.string "cust_instr"
    t.string "internal_instr"
    t.string "overtime_code"
    t.string "shift_day_cost"
    t.string "tr_code"
    t.string "tr_hours"
    t.string "tr_rate"
    t.boolean "pay_break"
    t.string "ref_source"
    t.string "memo"
    t.string "comment_1"
    t.string "comment_2"
    t.string "comment_3"
    t.boolean "confirmed_shift"
    t.string "role_type"
    t.string "std_shift_code"
    t.boolean "queue"
    t.boolean "tentative"
    t.string "booked_timekey"
    t.boolean "ot_authorised"
    t.string "confirmed_time_date"
    t.string "confirmed_by"
    t.string "ohead_code"
    t.string "ohead_rate"
    t.string "ohead_qty"
    t.string "chg_date"
    t.string "chg_fee_code"
    t.string "chg_hours"
    t.string "chg_rate"
    t.string "cas_chg_date"
    t.string "cas_chg_fee_code"
    t.string "cas_chg_hours"
    t.string "cas_chg_rate"
    t.boolean "adjusted_flag"
    t.string "cas_chg_narration"
    t.boolean "extend_base_charge"
    t.boolean "uninvoiced_status"
    t.boolean "charge_rate_oride"
    t.boolean "ops_confirmed_shift"
    t.string "ops_confirmed_by"
    t.string "ops_confirmed_time_date"
    t.string "creation_source"
    t.boolean "close_shift"
    t.boolean "split_shift"
    t.string "split_links"
    t.string "cas_chg_level"
    t.string "flat_pay_amount"
    t.string "flat_charge_amount"
    t.string "split_idx"
    t.string "split_charge_idx"
    t.boolean "charge_time_base_flag"
    t.string "add_allowance_codes"
    t.string "add_allowance_amount"
    t.string "add_allowance_source"
    t.string "add_allowance_notes"
    t.boolean "overide_breaktime"
    t.string "cas_timeband_start"
    t.string "cas_timeband_end"
    t.boolean "ivr_updated"
    t.string "handover_notes_key"
    t.string "chargeto_customer"
    t.boolean "add_allowance_all_hours"
    t.boolean "ot_cast_lock"
    t.string "sales_gl_acc"
    t.string "split_sub_client"
    t.string "split_client_pcnt"
    t.string "split_client_amount"
    t.string "import_batch"
    t.string "error_string"
    t.boolean "entry_valid"
    t.string "edit_hour_qty"
    t.string "edit_rate"
    t.string "master_roster"
    t.string "sub_roster"
    t.date "activity_date"
    t.string "post_date"
    t.string "tna_act_date"
    t.string "tna_round_date"
    t.string "tna_act_time"
    t.string "tna_round_time"
    t.string "tna_entry_type"
    t.string "tna_file_name"
    t.string "tna_log_id"
    t.string "tna_unit_id"
    t.string "base_hours"
    t.date "mbrk_break_out"
    t.string "mbrk_time_out"
    t.date "mbrk_break_in"
    t.string "mbrk_time_in"
    t.string "mbrk_overdue"
    t.string "mbrk_penalty"
    t.string "padj_codetype"
    t.string "padj_paycode"
    t.string "padj_diff_value"
    t.string "padj_diff_hours"
    t.string "permshift_tracking_no"
    t.string "pattern_code"
    t.string "audit_history_id"
    t.string "gender"
    t.boolean "cust_confirmed_shift"
    t.string "cust_confirmed_by"
    t.string "cust_confirmed_time_date"
    t.string "pymnt_claim"
    t.string "pymnt_claim_date"
    t.string "pymnt_claim_comment"
    t.string "shift_day_tsht_type"
    t.string "shift_day_tsht_code"
    t.string "shift_day_tsht_rate"
    t.string "shift_day_tsht_qty"
    t.string "required_skills"
    t.string "new_coy_debtor"
    t.string "new_coy_debtor_idx"
    t.string "ordered_by"
    t.string "cancelled_by"
    t.string "request_reason"
    t.string "auth_datetime"
    t.string "skill_auth_client"
    t.string "skill_auth_reason"
    t.string "tna_latitude"
    t.string "tna_longitude"
    t.boolean "activity_completed"
    t.string "feedback"
    t.string "survey"
    t.string "attachments"
    t.string "signature"
    t.string "ndis"
    t.string "ndis_authorised"
    t.string "excuses"
    t.boolean "disable_location_check"
    t.string "start_address"
    t.string "start_address2"
    t.string "start_suburb"
    t.string "start_state"
    t.string "start_postcode"
    t.string "end_address"
    t.string "end_address2"
    t.string "end_suburb"
    t.string "end_state"
    t.string "end_postcode"
    t.string "start_latitude"
    t.string "start_longitude"
    t.datetime "start_date"
    t.datetime "end_date"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["company_id"], name: "index_rosters_on_company_id"
    t.index ["customer", "employee_code"], name: "index_rosters_on_customer_and_employee_code"
  end

  create_table "users", force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "jti", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.boolean "is_admin", default: false
    t.bigint "company_id"
    t.integer "sign_in_count", default: 0, null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.inet "current_sign_in_ip"
    t.inet "last_sign_in_ip"
    t.integer "failed_attempts", default: 0, null: false
    t.string "unlock_token"
    t.datetime "locked_at"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["company_id"], name: "index_users_on_company_id"
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["jti"], name: "index_users_on_jti", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
    t.index ["unlock_token"], name: "index_users_on_unlock_token", unique: true
  end

end
