class CreateClients < ActiveRecord::Migration[6.0]
  def change
    create_table :clients do |t|
      t.references :company
      t.string :client_code # was common_code
      t.string :charge_code
      t.string :coy_debtor
      t.string :credit_terms
      t.string :client_type
      t.string :contract_no
      t.string :reference_no
      t.string :contract_date
      t.string :contract_completion
      t.string :contract_value
      t.string :billing_cycle
      t.string :contract_narration
      t.string :client_activated
      t.string :client_inactive
      t.string :cas_bill_cycle
      t.boolean :cas_consolidate
      t.string :cas_narration
      t.string :cas_fee_schedule
      t.string :std_start_time
      t.string :std_finish_time
      t.string :last_cycle
      t.boolean :cont_contract
      t.string :cont_repet_amt
      t.string :publichol
      t.string :cascode_rate1
      t.string :account_contact
      t.string :cascode_rate3
      t.string :cascode_rate4
      t.string :casrate1_oride
      t.string :casrate2_oride
      t.string :casrate3_oride
      t.string :casrate4_oride
      t.string :category
      t.string :cas_cat
      t.string :mon_svce_code
      t.string :mon_svce_rate
      t.boolean :monitoring
      t.string :generic_name
      t.string :last_gendate
      t.string :client_class # was class
      t.string :normal_day
      t.string :hours_pperiod
      t.string :repet_charge_ac
      t.string :repet_service_desc
      t.string :cas1_charge_to
      t.string :case2_charge_to
      t.string :cas3_charge_to
      t.string :cas4_charge_to
      t.string :monitoring_charge_to
      t.string :monitor_service_desc
      t.string :cas_category_description
      t.string :cost_method
      t.string :cost_rate
      t.string :std_hours_schedule
      t.string :client_category
      t.string :inv_jnl
      t.string :division
      t.string :department
      t.string :institution
      t.string :speciality
      t.string :beds
      t.string :occupancy
      t.string :contract_ref
      t.string :lab_attch_flag
      t.string :clab_attch_flag
      t.string :discount_code
      t.string :monitoring_class
      t.string :monitoring_company
      t.string :perm_payclass
      t.string :cas_payclass
      t.boolean :whcchge
      t.string :salesman
      t.string :debtor_clerk
      t.string :std_phol_schedule
      t.boolean :apply_stdhours
      t.string :rebate_ctrl
      t.string :rebate_cat
      t.string :rebate_code
      t.string :dflt_car
      t.string :charge_type
      t.string :minimum_hours
      t.boolean :fix_rate
      t.string :fixed_rate_period
      t.boolean :suppress_messages
      t.boolean :debtors_ledger
      t.string :cost_centre
      t.string :perm_grade
      t.string :cas_grade
      t.boolean :oncharge_ot
      t.boolean :time_scheduling
      t.string :review_date
      t.string :shift_names
      t.boolean :inactive
      t.string :area_bldg
      t.string :service_levels
      t.string :casual_service_desc
      t.string :region
      t.string :cas_cost_rate
      t.string :casinv_detail_lvl
      t.string :scheduling_seq
      t.string :response_inv_flag
      t.string :invoice_statement_flag
      t.boolean :invoice_ordno_split
      t.boolean :print_cust_bill_instructions
      t.boolean :print_response_on_invoice
      t.boolean :show_rate_type
      t.string :default_cost_centre
      t.string :response_time
      t.string :dflt_bud_emptype
      t.string :send_invoice_by
      t.string :email_address
      t.boolean :brief_required
      t.string :invoice_format
      t.string :addendum_format
      t.boolean :summ_rpt_option
      t.string :summ_rpt_narrative
      t.string :attach_files
      t.string :attach_comments
      t.string :seasonality_group
      t.boolean :role_rate_mapping
      t.string :vendor_cost_code
      t.boolean :apply_award_schedule
      t.boolean :roletype_split
      t.boolean :do_not_invoice
      t.string :store_no
      t.boolean :include_acn_invoice
      t.string :care_plans
      t.timestamps
    end
    add_index :clients, :client_code
  end
end
