class CreateRosters < ActiveRecord::Migration[6.0]
  def change
    create_table :rosters do |t|
      t.references :company
      t.string :employee_code
      t.string :long_id
      t.string :customer
      t.boolean :penalty
      t.string :fee_sched
      t.string :fee_code
      t.string :payclass
      t.string :btime
      t.string :paid_hours
      t.string :tsht_type
      t.string :tsht_code
      t.string :tsht_rate
      t.string :tsht_qty
      t.string :nml_code
      t.string :nml_hours
      t.string :nml_rate
      t.string :t12_code
      t.string :t12_hours
      t.string :t12_rate
      t.string :dbl_code
      t.string :dbl_hours
      t.string :dbl_rate
      t.string :oth_code
      t.string :oth_hours
      t.string :oth_rate
      t.string :abft_code
      t.string :abft_rate
      t.string :abft_qty
      t.string :dbft_code
      t.string :dbft_rate
      t.string :dbft_qty
      t.string :aaft_code
      t.string :aaft_rate
      t.string :aaft_qty
      t.string :daft_code
      t.string :daft_rate
      t.string :daft_qty
      t.string :shift_day
      t.string :shift_hours
      t.string :pay_details
      t.string :invoice_ref
      t.string :meal_brk_start
      t.string :meal_brk_end
      t.string :wrk_hrs_paid
      t.string :chg_shift_day
      t.string :chg_shift_hours
      t.boolean :unpaid_status
      t.boolean :casual
      t.string :activity_stime
      t.string :activity_etime
      t.string :activity_proj
      t.string :activity_task
      t.string :activity_details
      t.string :hour_type
      t.string :modified_by
      t.string :modified_date
      t.string :shift_zone
      t.string :time_code
      t.string :gl_codes
      t.string :cust_orderno
      t.string :fax_lodgement
      t.string :response_event
      t.string :cust_instr
      t.string :internal_instr
      t.string :overtime_code
      t.string :shift_day_cost
      t.string :tr_code
      t.string :tr_hours
      t.string :tr_rate
      t.boolean :pay_break
      t.string :ref_source
      t.string :memo
      t.string :comment_1
      t.string :comment_2
      t.string :comment_3
      t.boolean :confirmed_shift
      t.string :role_type
      t.string :std_shift_code
      t.boolean :queue
      t.boolean :tentative
      t.string :booked_timekey
      t.boolean :ot_authorised
      t.string :confirmed_time_date
      t.string :confirmed_by
      t.string :ohead_code
      t.string :ohead_rate
      t.string :ohead_qty
      t.string :chg_date
      t.string :chg_fee_code
      t.string :chg_hours
      t.string :chg_rate
      t.string :cas_chg_date
      t.string :cas_chg_fee_code
      t.string :cas_chg_hours
      t.string :cas_chg_rate
      t.boolean :adjusted_flag
      t.string :cas_chg_narration
      t.boolean :extend_base_charge
      t.boolean :uninvoiced_status
      t.boolean :charge_rate_oride
      t.boolean :ops_confirmed_shift
      t.string :ops_confirmed_by
      t.string :ops_confirmed_time_date
      t.string :creation_source
      t.boolean :close_shift
      t.boolean :split_shift
      t.string :split_links
      t.string :cas_chg_level
      t.string :flat_pay_amount
      t.string :flat_charge_amount
      t.string :split_idx
      t.string :split_charge_idx
      t.boolean :charge_time_base_flag
      t.string :add_allowance_codes
      t.string :add_allowance_amount
      t.string :add_allowance_source
      t.string :add_allowance_notes
      t.boolean :overide_breaktime
      t.string :cas_timeband_start
      t.string :cas_timeband_end
      t.boolean :ivr_updated
      t.string :handover_notes_key
      t.string :chargeto_customer
      t.boolean :add_allowance_all_hours
      t.boolean :ot_cast_lock
      t.string :sales_gl_acc
      t.string :split_sub_client
      t.string :split_client_pcnt
      t.string :split_client_amount
      t.string :import_batch
      t.string :error_string
      t.boolean :entry_valid
      t.string :edit_hour_qty
      t.string :edit_rate
      t.string :master_roster
      t.string :sub_roster
      t.date :activity_date
      t.string :post_date
      t.string :tna_act_date
      t.string :tna_round_date
      t.string :tna_act_time
      t.string :tna_round_time
      t.string :tna_entry_type
      t.string :tna_file_name
      t.string :tna_log_id
      t.string :tna_unit_id
      t.string :base_hours
      t.date :mbrk_break_out
      t.string :mbrk_time_out
      t.date :mbrk_break_in
      t.string :mbrk_time_in
      t.string :mbrk_overdue
      t.string :mbrk_penalty
      t.string :padj_codetype
      t.string :padj_paycode
      t.string :padj_diff_value
      t.string :padj_diff_hours
      t.string :permshift_tracking_no
      t.string :pattern_code
      t.string :audit_history_id
      t.string :gender
      t.boolean :cust_confirmed_shift
      t.string :cust_confirmed_by
      t.string :cust_confirmed_time_date
      t.string :pymnt_claim
      t.string :pymnt_claim_date
      t.string :pymnt_claim_comment
      t.string :shift_day_tsht_type
      t.string :shift_day_tsht_code
      t.string :shift_day_tsht_rate
      t.string :shift_day_tsht_qty
      t.string :required_skills
      t.string :new_coy_debtor
      t.string :new_coy_debtor_idx
      t.string :ordered_by
      t.string :cancelled_by
      t.string :request_reason
      t.string :auth_datetime
      t.string :skill_auth_client
      t.string :skill_auth_reason
      t.string :tna_latitude
      t.string :tna_longitude
      t.boolean :activity_completed
      t.string :feedback
      t.string :survey
      t.string :attachments
      t.string :signature
      t.string :ndis
      t.string :ndis_authorised
      t.string :excuses
      t.boolean :disable_location_check
      t.string :start_address
      t.string :start_address2
      t.string :start_suburb
      t.string :start_state
      t.string :start_postcode
      t.string :end_address
      t.string :end_address2
      t.string :end_suburb
      t.string :end_state
      t.string :end_postcode
      t.string :start_latitude
      t.string :start_longitude

      t.datetime :start_date
      t.datetime :end_date

      t.timestamps
    end
    add_index :rosters, [:customer, :employee_code]
  end
end
