 class CreateEmployee < ActiveRecord::Migration
   def change
     create_table :employees do |t|
       t.string :employee
       t.string :employee_a_street
       t.string :employee_a_suburb
       t.string :employee_a_post_code
       t.string :employee_a_city
       t.string :a_phone
       t.string :a_second_phone
       t.string :marital_status
       t.string :sex
       t.date :birth_date
       t.date :employment_date
       t.date :termination_date
       t.string :security_license_number
       t.date :security_license_expiry_date
       t.string :first_name
       t.string :middle_name
       t.string :surname
       t.string :employ_company
       t.string :pay_advice
       t.string :super_fund_no
       t.string :employment_type
       t.string :pay_class
       t.string :tax_file_number
       t.string :tax_schedule
       t.string :tax_rebates
       t.string :group_catagory
       t.string :bank_acc_name
       t.string :bank_bsb
       t.string :bank_acc_no
       t.string :payment_method
       t.string :allowance
       t.string :allow_amt
       t.string :sick_leave
       t.string :leave
       t.string :lsl
       t.string :super_fund
       t.string :bank_amount
       t.string :pay_cycle
       t.string :default_cost_ctr
       t.string :accrued_sick_leave
       t.string :accrued_annual_leave
       t.string :accrued_lsl
       t.string :accrued_rdo
       t.string :relatives_name
       t.string :relative_contact
       t.string :license_type
       t.string :emp_pay_ref
       t.boolean :hecs
       t.string :alias
       t.string :deduct_payee
       t.string :eft_lodgement_no
       t.string :coy_sgl
       t.string :vol_sgl
       t.string :vol_sgl_amt
       t.string :vol_policy
       t.string :rel_relation
       t.string :vested_coy_sgl
       t.string :vested_emp_sgl
       t.string :term_reas_code
       t.string :override_income
       t.string :override_base_hours
       t.boolean :apply_override_base_hours
       t.string :emp_class_oride
       t.string :alldedn_start
       t.string :alldedn_end
       t.string :alldedn_mthd
       t.string :alldedn_bal
       t.string :bcn
       t.string :leave_code_oride
       t.string :mobile_phone
       t.boolean :term_flag
       t.string :leave_base
       t.date :tax_waiver_date
       t.string :country
       t.string :photo_path
       t.string :preffered_name
       t.date :review_date
       t.string :personal_details
       t.string :weight
       t.string :height
       t.string :dependants
       t.string :other_notes
       t.string :ban_location
       t.date :ban_location_date
       t.string :ban_location_reason
       t.date :ban_location_end_date
       t.string :title
       t.string :former_name
       t.string :prev_name
       t.string :citizenship
       t.boolean :resident
       t.boolean :work_permit
       t.string :contact_types
       t.string :contact_numbers
       t.string :contact_notes
       t.string :pay_advice_delivery
       t.string :depend_surname
       t.string :depend_fname
       t.string :depend_relationship
       t.date :depend_birthdate
       t.boolean :rehire
       t.string :skill_code
       t.date :attain_date
       t.string :skill_comment
       t.boolean :oncall
       t.boolean :close_shifts
       t.boolean :long_week
       t.boolean :long_day
       t.string :role_types
       t.string :work_regions
       t.string :nationality
       t.boolean :sfss
       t.date :last_accrue_date
       t.boolean :print_bank_details
       t.string :cost_centre
       t.string :cost_centre_split
       t.string :class_change_date
       t.string :class_change_type
       t.string :class_change_class
       t.string :class_change_reason
       t.string :transfered_employeeid
       t.string :mail_address
       t.string :mail_suburb
       t.string :mail_state
       t.string :mail_postcode
       t.string :mail_country
       t.string :licence_image
       t.string :skills_image
       t.string :notes
       t.string :eff_entitle_date
       t.string :eff_aleave_code
       t.string :eff_sickleave_code
       t.string :eff_rdo_code
       t.string :eff_lsl_code
       t.string :position_group_code
       t.date :position_date
       t.date :system_start_date
       t.string :change_status
       t.string :super_change_date
       t.string :super_change_fund
       t.string :super_change_policy
       t.string :super_change_note
       t.boolean :pay_skill
       t.string :pay_location
       t.boolean :excess_hours_pref
       t.boolean :traineeship_flag
       t.date :training_review_date
       t.string :emp_email_address
       t.string :web_user_id
       t.string :latitude
       t.string :longitude
       t.string :status_date
       t.string :status_code
       t.string :inactive_date
       t.string :inactive_reason
       t.string :rehire_reason
       t.string :employee_logs
 
       t.timestamps null: false
     end
   end
 end
